Super fast search
18F/all_sorns pull request #116
Opened 2021-01-08 01:27 UTC by ondrae

This PR uses both a materialized view for our default search, then tsvector columns for when sections are selected.

#### ToDo:
- [ ] Add a call to refresh the materialized view after our daily update.

2021-01-13 18:53 UTC, ondrae commented on app/jobs/refresh_search_job.rb
> +class RefreshSearchJob < ApplicationJob
This job is here just if we need it later, depending on how the daily update gets implemented.

2021-01-14 14:49 UTC, lauraGgit requested changes
I have a few comments about error handling. I also think that the readme needs some documentation about your fast search implementation and references to the gems used.

2021-01-14 17:14 UTC, ondrae commented on app/controllers/sorns_controller.rb
> +  def filter_on_publication_date
Right, on it.

2021-01-14 17:18 UTC, ondrae commented on .github/workflows/deploy.yml
> +        image: postgres
The postgres "generated" column type was introduced in postgres:12. Locally and on cloud.gov we are on 13. We could pin it to 13 if we want to be specific.

2021-01-14 17:20 UTC, ondrae commented on spec/requests/search_csv_request_spec.rb
> +    FullSornSearch.refresh # refresh the materialized view
ooooh good idea, then we wouldn't have to remember to do it.

2021-01-14 17:22 UTC, ondrae commented
I've added all @lauraGgit suggestions to the top comment to work through. Thanks for the review.

2021-01-14 22:59 UTC, lauraGgit reviewed
LGTM.- I might take a look at the Kanmari issue that was popping up, but I wasn't able to reproduce locally.

2021-01-14 22:59 UTC, lauraGgit commented on spec/requests/search_request_spec.rb
> +  let!(:sorn) { create :sorn }
a neat example of the tests barely needing to change in the refactor!

2021-01-15 18:25 UTC, lauraGgit approved these changes

2021-01-15 18:30 UTC, merged