Agency short names and filtering
18F/all_sorns pull request #140
Opened 2021-01-21 19:49 UTC by ondrae

Uses the agency short names where we have them.
<img width="667" alt="Screen Shot 2021-01-14 at 5 18 40 PM" src="https://user-images.githubusercontent.com/595778/104668532-1f462400-568d-11eb-90df-4ca82b44616f.png">

Can filter on the long list of agency names. Does some clever js to still include checked but not visible agencies in the next search.

<img width="335" alt="Screen Shot 2021-01-14 at 5 21 02 PM" src="https://user-images.githubusercontent.com/595778/104668575-35ec7b00-568d-11eb-8a23-28c7757200e3.png">

Can also filter by short name.
<img width="338" alt="Screen Shot 2021-01-14 at 5 20 41 PM" src="https://user-images.githubusercontent.com/595778/104668672-63d1bf80-568d-11eb-911d-4657fdb27ac9.png">

Closes #89 

There was a different attempt at this in a closed PR #123

2021-01-22 01:37 UTC, ondrae commented
Hmmm, I may having search be on its own route, and only load the js then.

2021-01-29 17:12 UTC, peterrowland requested changes
@iamjolly gave us some some [a11y recommendations](https://github.com/18F/all_sorns/issues/155) for this

2021-02-04 00:40 UTC, ondrae commented
Added a label and the search filtering help text in a screen reader friendly way.
<img width="340" alt="Screen Shot 2021-02-03 at 4 39 08 PM" src="https://user-images.githubusercontent.com/595778/106828122-65642700-663e-11eb-945d-0fbd66153d0d.png">

2021-02-04 00:43 UTC, ondrae commented on app/views/layouts/application.html.erb
> +      <!-- Only load cusotm js if there is an active search -->
```suggestion
      <!-- Only load custom js if there is an active search -->
```

2021-02-04 17:50 UTC, peterrowland approved these changes

2021-02-04 19:33 UTC, merged