[WIP] Update button
18F/all_sorns pull request #172
Opened 2021-02-19 19:07 UTC by igorkorenfeld

WIP for option 2 in #169 , adding in an apply filters button 

- Adds apply button on change of selected filters
- Adjusts styling of the filters section to make it more distinct from the main section
- Limits height of the filters sidebar so the user can see the content didn't refresh 

![image](https://user-images.githubusercontent.com/52677065/108549641-6db59680-72bb-11eb-9c73-b79e6f2da34f.png)

2021-02-19 22:56 UTC, peterrowland commented
TODOs:
NaN re-appearing
why does the page reload when clearing all agency/section filters?
Should it show apply filters when date filters are removed?

2021-02-19 23:04 UTC, igorkorenfeld commented
From  the conversation with @peterrowland 
Outline for tests

### 1
- select agency checkbox
- select section checkbox
- expect 

### 2
- add date range 
- expect applyBtn

### 3   
- select agnecy checkbox
- deselect same agency checkbox
- expect applyBtn.length === 0
### 4
- After load with filters
- expect applyBtn.length === 0
- No apply 


Also need to check on behavior for when "Clear all" buttons is pressed with respect to apply filters button

2021-02-25 15:41 UTC, lauraGgit reviewed
haven't had a chance to review locally, but here are some initiall comments

2021-02-25 15:41 UTC, lauraGgit commented on app/assets/stylesheets/application.scss
> +  padding-left: 0.5em;
you can shorten this by changing it to `padding: 0.25em 0.5em`

2021-02-25 15:41 UTC, lauraGgit commented on app/javascript/packs/search.js
> +      else {
to DRY this up you could initialize the value as false and then only make a single conditional that sets the value to `true`

2021-02-25 15:41 UTC, lauraGgit commented on app/javascript/packs/search.js
> +      if (isNaN(initialStartDate) && isNaN(currentStartDate) && isNaN(initialEndDate) && isNaN(currentEndDate)) {
it seems like you might effectively be doing this date validation twice on the current dates. you might want to consider writing it to only need to check once.

2021-02-25 15:41 UTC, lauraGgit commented on app/javascript/packs/search.js
> +    return true;
given that there are 4 cases here, I would initialize a variable as either `true/false` and then update the cases to return that variable as that could dry this up a bit.

2021-02-26 22:31 UTC, ondrae requested changes
If I type something into the agency filter box and hit the enter button, all the buttons and links that would submit get disabled.
![Screen Shot 2021-02-26 at 2 30 02 PM](https://user-images.githubusercontent.com/595778/109362140-43c21e00-783f-11eb-9f38-d5bb75f5ce4a.png)

Update: Oooooh it's an existing bug. It happens on production too.

2021-02-26 23:14 UTC, ondrae requested changes
This `showActiveFilters` method needs an opposite too. I ended up with a blank `#active-filters` area by adding some filters then removing them, before submitting.

![Screen Shot 2021-02-26 at 3 02 51 PM](https://user-images.githubusercontent.com/595778/109364900-af5aba00-7844-11eb-93e8-fed5e9d3905d.png)

A test for this can go in the spec/system/search_spec.rb file, adding some filters, removing them then asserting `expect(page).to have_selector("#active-filters", visible: false)`

2021-02-26 23:14 UTC, ondrae commented on app/javascript/packs/search.js
> +    }
```suggestion
    showActiveFilters();
```

This method was added below, use it here.

2021-03-01 20:34 UTC, igorkorenfeld commented
@ondrae should #173 be merged before this one, this one first, or either way?

2021-03-02 18:17 UTC, ondrae approved these changes
Great work @igorkorenfeld

2021-03-02 18:18 UTC, merged