[Snyk] Security upgrade @rails/webpacker from 4.3.0 to 5.2.0
18F/all_sorns pull request #192
Opened 2021-03-15 03:21 UTC by its-a-lisa-at-work

<h3>Snyk has created this PR to fix one or more vulnerable packages in the `yarn` dependencies of this project.</h3>

![merge advice](https://app.snyk.io/badges/merge-advice/?package_manager=yarn&package_name=@rails/webpacker&from_version=4.3.0&to_version=5.2.0&pr_id=a573911f-af5a-4afc-88b6-457ea6f487db&visibility=true&has_feature_flag=false)

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - package.json
    - yarn.lock

#### Vulnerabilities that will be fixed
##### With an upgrade:
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
![high severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/h.png "high severity")  |  **661/1000**  <br/> **Why?** Recently disclosed, Has a fix available, CVSS 7.5  | Regular Expression Denial of Service (ReDoS) <br/>[SNYK-JS-SSRI-1085630](https://snyk.io/vuln/SNYK-JS-SSRI-1085630) |  Yes  | No Known Exploit 

(*) Note that the real score may have changed since the PR was raised.

Check the changes in this PR to ensure they won't cause issues with your project.

------------

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs.*

For more information:  <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiJhNTczOTExZi1hZjVhLTRhZmMtODhiNi00NTdlYTZmNDg3ZGIiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6ImE1NzM5MTFmLWFmNWEtNGFmYy04OGI2LTQ1N2VhNmY0ODdkYiJ9fQ==" width="0" height="0"/>
🧐 [View latest project report](https://app.snyk.io/org/tts/project/5f0f5410-719d-4ceb-a043-651db36f0e71)

🛠 [Adjust project settings](https://app.snyk.io/org/tts/project/5f0f5410-719d-4ceb-a043-651db36f0e71/settings)

📚 [Read more about Snyk's upgrade and patch logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

[//]: # (snyk:metadata:{"prId":"a573911f-af5a-4afc-88b6-457ea6f487db","dependencies":[{"name":"@rails/webpacker","from":"4.3.0","to":"5.2.0"}],"packageManager":"yarn","projectPublicId":"5f0f5410-719d-4ceb-a043-651db36f0e71","projectUrl":"https://app.snyk.io/org/tts/project/5f0f5410-719d-4ceb-a043-651db36f0e71?utm_source=github&utm_medium=fix-pr","type":"auto","patch":[],"vulns":["SNYK-JS-SSRI-1085630"],"upgrade":["SNYK-JS-SSRI-1085630"],"isBreakingChange":true,"env":"prod","prType":"fix","templateVariants":["updated-fix-title","priorityScore","merge-advice-badge-shown"],"priorityScoreList":[661]})

2021-03-16 18:25 UTC, ondrae commented
Looks like we need to bump up node in the test env https://github.com/18F/all_sorns/blob/main/.github/workflows/test.yml#L41

2021-03-16 19:17 UTC, folksgl commented
The Gemfile will need to be updated as well to not include the offending webpacker version, correct @ondrae?

2021-03-23 23:43 UTC, ondrae commented
I bumped the version of node and webpacker. I don't know what version of node we want to be at, 12.13.1 is just what I happened to have locally. Feel free to change it if you know of a better choice.

2021-03-24 20:51 UTC, folksgl commented
@ondrae The latest version of Node looks like 14.16.0. Is there a compelling reason not to use that? Would buy us some time before we have to update again if it passes all the tests. If we don't mind accepting minor version bumps on node we can also just specify '14' according to https://github.com/actions/setup-node

2021-03-24 20:57 UTC, folksgl commented on .github/workflows/test.yml
> +          node-version: 12.13.1
See the "Conversations" tab on the versions available for Node.

2021-03-24 20:58 UTC, folksgl requested changes
Can we test with the latest '14' version and see what happens?

2021-03-24 23:09 UTC, ondrae commented
Node v14 worked. Ship it!

2021-03-25 13:08 UTC, folksgl approved these changes

2021-03-25 13:10 UTC, merged